### ISSUE TITLE
Andorra and Australia

### ISSUE THREAD

**Issue by jrlumbang** [nikhiln/ngx-international-phone-number#31] opened 2019-02-21 01:11 UTC
When +61 (Australia country code) is typed in, Andorra is selected instead of Australia.

Another way to replicate the issue is:
- Select Australia from the drop down.
- Type a digit.
- Australia is changed to Andorra.

![image](https://user-images.githubusercontent.com/3758817/53136285-661e6280-35b9-11e9-887c-df9a17cf20c3.png)

**Comment by AdGalesso** [comment] 2019-02-21 06:35
The problem is not Andorra but Christmas Island because it uses ranges owned by Australia.

https://en.wikipedia.org/wiki/Telephone_numbers_in_Christmas_Island

So I think in this case Christmas Island shouldn't be there? 

![phone](https://user-images.githubusercontent.com/6923573/53148516-fdf26f80-35fe-11e9-8250-5594ea9bd60c.jpg)

**Comment by nikhiln** [comment] 2019-03-10 06:15
Closing this based on fixes from #32

**Closed by nikhiln** 2019-03-10 06:15 UTC
Labels: help wanted
